apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      namespace: default
      name: service-reader
    rules:
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "list", "watch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: service-reader-binding
      namespace: default
    subjects:
    - kind: User
      name: "arn:aws:iam::992382573619:user/Piyush_Sharma"  # Replace with your IAM user ARN
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: Role
      name: service-reader
      apiGroup: rbac.authorization.k8s.io

